import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, Validators, ReactiveFormsModule } from '@angular/forms';
import { Filiale } from '../../../Models/filiale.model';
import { Router, RouterModule } from '@angular/router';
import { FilialeService } from '../../shared/services/filiale.service';
import { CommonModule } from '@angular/common';
import { Observable } from 'rxjs';

@Component({
  selector: 'app-filiale-add',
  templateUrl: './filiale-add.component.html',
  styleUrls: ['./filiale-add.component.css'],
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule, RouterModule]
})
export class FilialeAddComponent implements OnInit {
  filialeForm: FormGroup;
  errorMessage: string | null = null;
  successMessage: string | null = null;
  selectedFile: File | null = null;
  photo: string | null = null;  // For image preview
  isLoading: boolean = false;

  constructor(
    private fb: FormBuilder,
    private filialeService: FilialeService,
    private router: Router
  ) {
    this.filialeForm = this.fb.group({
      nom: ['', [Validators.required, Validators.minLength(2)]],
      adresse: ['', [Validators.required, Validators.minLength(5)]],
      description: [''],
      dateCreation: ['', Validators.required]
    });
  }

  ngOnInit(): void {
    // No initialization needed for add mode since we create a new filiale
  }

  onFileChange(event: Event): void {
    const input = event.target as HTMLInputElement;
    if (input.files && input.files.length > 0) {
      this.selectedFile = input.files[0];
      this.previewPhoto();
    }
  }

  previewPhoto(): void {
    if (this.selectedFile) {
      const reader = new FileReader();
      reader.onload = (e: any) => {
        this.photo = e.target.result as string;
      };
      reader.readAsDataURL(this.selectedFile);
    }
  }

  uploadPhoto(): Promise<string> {
    return new Promise((resolve, reject) => {
      if (!this.selectedFile) {
        resolve(this.photo || '');
        return;
      }
      this.isLoading = true;
      this.filialeService.uploadPhoto(this.selectedFile).subscribe({
        next: (response) => {
          this.isLoading = false;
          resolve(response.url);
        },
        error: (error) => {
          this.isLoading = false;
          this.errorMessage = 'Erreur lors de l\'upload de la photo : ' + error.message;
          reject(error);
        }
      });
    });
  }

  async onSubmit(): Promise<void> {
    if (this.filialeForm.invalid) {
      this.errorMessage = 'Veuillez remplir tous les champs requis correctement';
      return;
    }

    this.isLoading = true;
    this.errorMessage = null;
    this.successMessage = null;

    let photoUrl = this.photo || '';
    if (this.selectedFile) {
      try {
        photoUrl = await this.uploadPhoto();
      } catch (error) {
        return;
      }
    }

    // Create a new filiale payload; the idFiliale is empty and will be generated by the backend
    const filiale: Filiale = {
      idFiliale: '',
      nom: this.filialeForm.get('nom')?.value,
      adresse: this.filialeForm.get('adresse')?.value,
      description: this.filialeForm.get('description')?.value || '',
      dateCreation: new Date(this.filialeForm.get('dateCreation')?.value),
      photo: photoUrl
    };

    this.saveFiliale(filiale);
  }

  saveFiliale(filiale: Filiale): void {
    const action$: Observable<Filiale> = this.filialeService.addFiliale(filiale);
    action$.subscribe({
      next: () => {
        this.successMessage = 'Filiale ajoutée avec succès !';
        this.isLoading = false;
        setTimeout(() => this.router.navigate(['/admin/filiales']), 1500);
      },
      error: (err: any) => {
        this.errorMessage = "Erreur lors de l'ajout : " + (err.message || err.statusText || 'Une erreur est survenue');
        this.isLoading = false;
      }
    });
  }

  // Getters for form controls
  get nom() { return this.filialeForm.get('nom'); }
  get adresse() { return this.filialeForm.get('adresse'); }
  get dateCreation() { return this.filialeForm.get('dateCreation'); }
}